import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav>
          <ul>
            <li><Link href="/" style={{color:"#df1721ff"}}>首页</Link></li>
            <li><Link href="/about" style={{color:"#df1721ff"}}>关于</Link></li>
            <li><Link href="/dashboard" style={{color:"#df1721ff"}}>后台管理系统</Link></li>
          </ul>
        </nav>
        {/* 渲染当前访问的那个page.tsx */}
        {children}
        </body>
    </html>
  );
}
