# nginx.conf
# Nginx 程序住在 docker 容器 (Linux 小盒子)；你的业务程序住在外面 Windows 主机。
event{

}

http{
    server{
        listen 80;
        proxy_pass http://host.docker.internal:1314;
        proxy_set_header Host $host;
    }
}